services:
  api:
    build:
      context: ./services/api
      dockerfile: Dockerfile
    ports: ["${API_PORT}:3000"]
    env_file:
      - ./.env
    depends_on:
      - auth

  auth:
    build:
      context: ./services/auth
      dockerfile: Dockerfile
    ports:
      - "${AUTH_PORT}:4000"
    env_file:
      - ./.env
