version: "3.9"

services:
  db:
    image: postgres:15-alpine
    container_name: habits-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: habitsdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d habitsdb"]
      interval: 5s
      timeout: 5s
      retries: 20

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: habits-api
    depends_on:
      db:
        condition: service_healthy
    environment:
      # psycopg3 driver (matchar dina deps)
      DATABASE_URL: postgresql+psycopg://postgres:postgres@db:5432/habitsdb
      # lägg fler här, t.ex. JWT_SECRET etc
    ports:
      - "8000:8000"
    command: >
      uvicorn app.main:app
      --host 0.0.0.0 --port 8000 --reload
    volumes:
      # hot reload av koden lokalt (valfritt, men najs i dev)
      - ./backend:/app

volumes:
  db_data:
