name: Backend CI

on:
  push:
    paths: ["backend/**", ".github/workflows/backend.yml"]
  pull_request:
    paths: ["backend/**", ".github/workflows/backend.yml"]

jobs:
  test:
    runs-on: ubuntu-latest

    # Start a Postgres container in Actions
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: habitsdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres -d habitsdb"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=20

    defaults:
      run:
        working-directory: backend

    # Make your app code importable + set DB URL för psycopg3
    env:
      PYTHONPATH: .
      DATABASE_URL: postgresql+psycopg://postgres:postgres@localhost:5432/habitsdb

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements-dev.txt

      # Optional but good to have - wait until DB is ready
      - name: Wait for Postgres
        run: |
          for i in {1..50}; do
            pg_isready -h localhost -p 5432 -d habitsdb -U postgres && s=0 && break || s=$?
            echo "Postgres not ready yet ($i)..."
            sleep 2
          done
          exit $s

      - name: Run tests
        run: pytest -q --cov=app --cov-report=xml
