name: Frontend CI

on:
    push:
        branches:
            - main
            - v34

jobs:
    Hello:
        runs-on: ubuntu-latest

        steps:
            - name: Check out code
              run: actions/checkout@v3

            - name: Install Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "18"

            - name: Install dependencies
              working-directory: ./frontend
              run: npm install

            - name: Run tests
              working-directory: ./frontend
              run: npm test

            - name: Build project
              working-directory: ./frontend
              run: npm run build
