name: CI

on:
  push:
    branches: [main, dev]
  pull_request:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Build Docker image
        run: docker build -t alicegmn/habits:latest .

      - name: Log in to Docker Hub
        if: github.ref == 'refs/heads/main' || github.event_name == 'release'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        if: github.ref == 'refs/heads/main'
        run: |
          docker tag alicegmn/habits:latest alicegmn/habits:${{ github.sha }}
          docker push alicegmn/habits:latest
          docker push alicegmn/habits:${{ github.sha }}

      - name: Push Docker image with release tag
        if: github.event_name == 'release'
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "Pushing release version: $VERSION"
          docker tag alicegmn/habits:latest alicegmn/habits:$VERSION
          docker push alicegmn/habits:$VERSION
