name: Docker CI/CD

on:
    push:
        branches:
            - v36

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Check out code
              uses: actions/checkout@v3

            - name: Log in to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build and test image
              run: docker build --target build -t simple-server-test .

    build-and-push:
        runs-on: ubuntu-latest
        needs: test
        steps:
            - name: Check out code
              uses: actions/checkout@v3

            - name: Log in to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build runtime image
              run: docker build --target production -t simple-server:latest .

            - name: Push runtime image
              run: docker push simple-server:latest
