name: Simple Frontend CI/CD

on:
  push:
    branches:
      - simple-dev
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - simple-dev

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job

    steps:
      # --- Checkout repo ---
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false

      # --- Setup Node ---
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"
          cache-dependency-path: simple-frontend/package-lock.json

      # --- Install dependencies ---
      - name: Install dependencies
        working-directory: simple-frontend
        run: npm ci

      # --- Build frontend ---
      - name: Build frontend
        working-directory: simple-frontend
        run: npm run build

      # --- Deploy built app to Azure Static Web App ---
      - name: Deploy to Azure Static Web App
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PROUD_GLACIER_08CFB2D03 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "simple-frontend"
          output_location: "dist"
          api_location: ""

  # --- Close PR Deployment ---
  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_PROUD_GLACIER_08CFB2D03 }}
          action: "close"
